# Generated by Django 4.1.2 on 2022-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='date',
        ),
        migrations.AddField(
            model_name='students',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='rollno',
            field=models.IntegerField(default=''),
        ),
    ]
