# Generated by Django 4.1.2 on 2022-11-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_students_date_students_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRegistration', models.DateField(auto_now=True)),
                ('noOfCoupons', models.IntegerField(default=55)),
                ('dateOfExpiry', models.DateField(auto_now=True)),
                ('amt', models.IntegerField(default=3200)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.students')),
            ],
        ),
    ]
