# Generated by Django 4.1.2 on 2022-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='dateOfExpiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mess',
            name='dateOfRegistration',
            field=models.DateField(),
        ),
    ]
