# Generated by Django 4.1.2 on 2022-11-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_mess_dateofexpiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'FoodItem',
                'verbose_name_plural': 'FoodItems',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('meal_type', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AlterModelOptions(
            name='mess',
            options={'verbose_name': 'Mess', 'verbose_name_plural': 'Mess'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='home.fooditems')),
                ('scheduled_meal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.schedule')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
