# Generated by Django 4.1.2 on 2022-11-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fooditems_schedule_alter_mess_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='item',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
