# Generated by Django 4.1.2 on 2022-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_fooditems_item_alter_schedule_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='meal_type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=10),
        ),
    ]
