# Generated by Django 4.1.2 on 2022-11-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_schedule_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item',
            new_name='dish',
        ),
    ]
