# Generated by Django 4.1.2 on 2022-11-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_item_menu_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mess',
            options={'verbose_name': 'MessRegister', 'verbose_name_plural': 'MessRegister'},
        ),
    ]
