# Generated by Django 4.1.2 on 2022-11-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_mess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=500)),
                ('dateOfFeedback', models.DateField(auto_now_add=True)),
                ('meal_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='home.schedule')),
            ],
        ),
    ]
